# Example configuration showing all newly supported providers
agents:
    trae_agent:
        enable_lakeview: true
        model: lingxi_model  # Change this to use different providers
        max_steps: 200
        tools:
            - bash
            - str_replace_based_edit_tool
            - sequentialthinking
            - json_formatter
            - task_done

allow_mcp_servers:
    - playwright

mcp_servers:
    playwright:
        command: npx
        args:
            - "@playwright/mcp@0.0.27"

lakeview:
    model: lingxi_model

# Configuration for all new providers
model_providers:
    lingxi:
        api_key: your_lingxi_api_key
        provider: lingxi
        base_url: https://antchat.alipay.com/v1

    kimi:
        api_key: your_kimi_api_key
        provider: kimi
        base_url: https://api.moonshot.cn/v1

    deepseek:
        api_key: your_deepseek_api_key
        provider: deepseek
        base_url: https://api.deepseek.com

# Model configurations for each provider
models:
    # Lingxi models
    lingxi_model:
        model_provider: lingxi
        model: qwen3-coder-plus
        max_tokens: 4096
        temperature: 0.1
        top_p: 1
        top_k: 0
        max_retries: 10
        parallel_tool_calls: true

    # Kimi models
    kimi_model:
        model_provider: kimi
        model: moonshot-v1-8k  # Options: moonshot-v1-8k, moonshot-v1-32k, moonshot-v1-128k
        max_tokens: 4096
        temperature: 0.1
        top_p: 1
        top_k: 0
        max_retries: 10
        parallel_tool_calls: true

    # DeepSeek models
    deepseek_model:
        model_provider: deepseek
        model: deepseek-coder  # Options: deepseek-coder, deepseek-chat
        max_tokens: 4096
        temperature: 0.1
        top_p: 1
        top_k: 0
        max_retries: 10
        parallel_tool_calls: true