# Example configuration for DeepSeek provider
agents:
    trae_agent:
        enable_lakeview: true
        model: deepseek_model
        max_steps: 200
        tools:
            - bash
            - str_replace_based_edit_tool
            - sequentialthinking
            - json_formatter
            - task_done

allow_mcp_servers:
    - playwright

mcp_servers:
    playwright:
        command: npx
        args:
            - "@playwright/mcp@0.0.27"

lakeview:
    model: deepseek_model

model_providers:
    deepseek:
        api_key: your_deepseek_api_key
        provider: deepseek
        base_url: https://api.deepseek.com

models:
    deepseek_model:
        model_provider: deepseek
        model: deepseek-coder  # or deepseek-chat
        max_tokens: 4096
        temperature: 0.1
        top_p: 1
        top_k: 0
        max_retries: 10
        parallel_tool_calls: true