agents:
    trae_agent:
        enable_lakeview: true
        model: trae_agent_model
        max_steps: 200
        tools:
            - bash
            - str_replace_based_edit_tool
            - sequentialthinking
            - task_done
            - json_formatter
allow_mcp_servers:
    - playwright
mcp_servers:
    playwright:
        command: npx
        args:
            - "@playwright/mcp@0.0.27"
lakeview:
    model: lakeview_model

model_providers:
    dashscope:
        api_key: sk-abb054210aaa49d69cf797b925432ee5
        provider: dashscope

models:
    trae_agent_model:
        model_provider: dashscope
        model: qwen3-next-80b-a3b-instruct
        max_tokens: 4096
        temperature: 0.5
        top_p: 1
        top_k: 0
        max_retries: 10
        parallel_tool_calls: true
    lakeview_model:
        model_provider: dashscope
        model: qwen3-next-80b-a3b-instruct
        max_tokens: 4096
        temperature: 0.5
        top_p: 1
        top_k: 0
        max_retries: 10
        parallel_tool_calls: true